game:
  version:
    ${version}

logging:
  level:
    root: info

spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa